// Mock data for demo/showcase mode
import { TShop, TProduct, TOrder } from "@/types";

export const DEMO_SHOP: TShop = {
  id: "demo-shop-001",
  owner_id: "demo-user-001",
  name: "Boulangerie Marie",
  slug: "boulangerie-marie",
  description: "Artisan boulanger depuis 1987",
  logo_url: null,
  phone: "06 12 34 56 78",
  address: "12 rue de la Paix, 75002 Paris",
  welcome_message: "Bonjour ! Que souhaitez-vous commander ?",
  opening_hours: {},
  instagram_account_id: null,
  instagram_page_access_token: null,
  whatsapp_number: "+33612345678",
  stripe_account_id: "acct_demo123",
  stripe_subscription_id: null,
  stripe_customer_id: null,
  plan: "pro",
  commission_rate: 0.015,
  is_active: true,
  settings: {},
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};

export const DEMO_PRODUCTS: TProduct[] = [
  {
    id: "prod-001",
    shop_id: "demo-shop-001",
    name: "Croissant beurre",
    description: "Pur beurre AOP, feuilletage maison",
    price: 1.3,
    photo_url: "https://images.unsplash.com/photo-1555507036-ab1f4038024a?w=400&h=300&fit=crop&q=80",
    category: "Viennoiseries",
    is_available: true,
    sort_order: 0,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "prod-002",
    shop_id: "demo-shop-001",
    name: "Pain au chocolat",
    description: "Deux barres de chocolat noir 70%",
    price: 1.4,
    photo_url: "https://images.unsplash.com/photo-1530610476181-d83430b64dcd?w=400&h=300&fit=crop&q=80",
    category: "Viennoiseries",
    is_available: true,
    sort_order: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "prod-003",
    shop_id: "demo-shop-001",
    name: "Baguette tradition",
    description: "Farine Label Rouge, 24h de fermentation",
    price: 1.5,
    photo_url: "https://images.unsplash.com/photo-1549931319-a545753467c8?w=400&h=300&fit=crop&q=80",
    category: "Pains",
    is_available: true,
    sort_order: 2,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "prod-004",
    shop_id: "demo-shop-001",
    name: "Pain de campagne",
    description: "Melange seigle et froment, mie dense",
    price: 3.2,
    photo_url: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&h=300&fit=crop&q=80",
    category: "Pains",
    is_available: true,
    sort_order: 3,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "prod-005",
    shop_id: "demo-shop-001",
    name: "Tarte aux pommes",
    description: "Pommes caramelisees, pate brisee maison",
    price: 3.5,
    photo_url: "https://images.unsplash.com/photo-1568571780765-9276ac8b75a2?w=400&h=300&fit=crop&q=80",
    category: "Patisseries",
    is_available: true,
    sort_order: 4,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "prod-006",
    shop_id: "demo-shop-001",
    name: "Eclair au chocolat",
    description: "Creme patissiere chocolat, glacage miroir",
    price: 4.0,
    photo_url: "https://images.unsplash.com/photo-1587536849024-daaa4a417b16?w=400&h=300&fit=crop&q=80",
    category: "Patisseries",
    is_available: true,
    sort_order: 5,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "prod-007",
    shop_id: "demo-shop-001",
    name: "Sandwich jambon-beurre",
    description: "Jambon blanc, beurre demi-sel, baguette tradition",
    price: 4.5,
    photo_url: "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=400&h=300&fit=crop&q=80",
    category: "Snacking",
    is_available: true,
    sort_order: 6,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "prod-008",
    shop_id: "demo-shop-001",
    name: "Quiche lorraine",
    description: "Lardons, gruyere, creme fraiche",
    price: 4.2,
    photo_url: "https://images.unsplash.com/photo-1608855238293-a8853e7f7c98?w=400&h=300&fit=crop&q=80",
    category: "Snacking",
    is_available: true,
    sort_order: 7,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "prod-009",
    shop_id: "demo-shop-001",
    name: "Flan patissier",
    description: "Recette traditionnelle, vanille bourbon",
    price: 2.8,
    photo_url: "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400&h=300&fit=crop&q=80",
    category: "Patisseries",
    is_available: false,
    sort_order: 8,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "prod-010",
    shop_id: "demo-shop-001",
    name: "Cafe expresso",
    description: "Blend arabica torrefie artisanalement",
    price: 1.5,
    photo_url: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefda?w=400&h=300&fit=crop&q=80",
    category: "Boissons",
    is_available: true,
    sort_order: 9,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

const now = new Date();
const h = (hoursAgo: number) =>
  new Date(now.getTime() - hoursAgo * 60 * 60 * 1000).toISOString();
const m = (minutesAgo: number) =>
  new Date(now.getTime() - minutesAgo * 60 * 1000).toISOString();

export const DEMO_ORDERS: TOrder[] = [
  {
    id: "order-001",
    shop_id: "demo-shop-001",
    order_number: 1,
    customer_name: "Lucas M.",
    customer_phone: "+33678901234",
    customer_email: null,
    customer_channel: "whatsapp",
    items: [
      { product_id: "prod-001", name: "Croissant beurre", qty: 3, unit_price: 1.3, subtotal: 3.9 },
      { product_id: "prod-002", name: "Pain au chocolat", qty: 2, unit_price: 1.4, subtotal: 2.8 },
    ],
    subtotal: 6.7,
    commission_amount: 0.1,
    total: 6.7,
    status: "pending",
    payment_status: "paid",
    stripe_payment_intent_id: null,
    stripe_payment_link_id: null,
    stripe_payment_link_url: null,
    notes: null,
    created_at: m(3),
    updated_at: m(3),
    ready_at: null,
    picked_up_at: null,
    cancelled_at: null,
  },
  {
    id: "order-002",
    shop_id: "demo-shop-001",
    order_number: 2,
    customer_name: "Sophie D.",
    customer_phone: null,
    customer_email: "sophie@email.com",
    customer_channel: "widget",
    items: [
      { product_id: "prod-003", name: "Baguette tradition", qty: 2, unit_price: 1.5, subtotal: 3.0 },
      { product_id: "prod-005", name: "Tarte aux pommes", qty: 1, unit_price: 3.5, subtotal: 3.5 },
      { product_id: "prod-010", name: "Cafe expresso", qty: 2, unit_price: 1.5, subtotal: 3.0 },
    ],
    subtotal: 9.5,
    commission_amount: 0.14,
    total: 9.5,
    status: "preparing",
    payment_status: "paid",
    stripe_payment_intent_id: null,
    stripe_payment_link_id: null,
    stripe_payment_link_url: null,
    notes: "Sans sucre pour les cafes svp",
    created_at: m(12),
    updated_at: m(8),
    ready_at: null,
    picked_up_at: null,
    cancelled_at: null,
  },
  {
    id: "order-003",
    shop_id: "demo-shop-001",
    order_number: 3,
    customer_name: "Karim B.",
    customer_phone: "+33612345678",
    customer_email: null,
    customer_channel: "whatsapp",
    items: [
      { product_id: "prod-007", name: "Sandwich jambon-beurre", qty: 1, unit_price: 4.5, subtotal: 4.5 },
      { product_id: "prod-008", name: "Quiche lorraine", qty: 1, unit_price: 4.2, subtotal: 4.2 },
    ],
    subtotal: 8.7,
    commission_amount: 0.13,
    total: 8.7,
    status: "ready",
    payment_status: "pay_on_pickup",
    stripe_payment_intent_id: null,
    stripe_payment_link_id: null,
    stripe_payment_link_url: null,
    notes: null,
    created_at: m(25),
    updated_at: m(5),
    ready_at: m(5),
    picked_up_at: null,
    cancelled_at: null,
  },
  {
    id: "order-004",
    shop_id: "demo-shop-001",
    order_number: 4,
    customer_name: "Claire F.",
    customer_phone: null,
    customer_email: "claire.f@gmail.com",
    customer_channel: "instagram",
    items: [
      { product_id: "prod-006", name: "Eclair au chocolat", qty: 4, unit_price: 4.0, subtotal: 16.0 },
      { product_id: "prod-001", name: "Croissant beurre", qty: 6, unit_price: 1.3, subtotal: 7.8 },
    ],
    subtotal: 23.8,
    commission_amount: 0.36,
    total: 23.8,
    status: "picked_up",
    payment_status: "paid",
    stripe_payment_intent_id: null,
    stripe_payment_link_id: null,
    stripe_payment_link_url: null,
    notes: "Pour un anniversaire",
    created_at: h(1.5),
    updated_at: m(40),
    ready_at: h(1),
    picked_up_at: m(40),
    cancelled_at: null,
  },
  {
    id: "order-005",
    shop_id: "demo-shop-001",
    order_number: 5,
    customer_name: "Antoine R.",
    customer_phone: "+33698765432",
    customer_email: null,
    customer_channel: "whatsapp",
    items: [
      { product_id: "prod-004", name: "Pain de campagne", qty: 1, unit_price: 3.2, subtotal: 3.2 },
    ],
    subtotal: 3.2,
    commission_amount: 0.05,
    total: 3.2,
    status: "pending",
    payment_status: "pending",
    stripe_payment_intent_id: null,
    stripe_payment_link_id: null,
    stripe_payment_link_url: null,
    notes: null,
    created_at: m(1),
    updated_at: m(1),
    ready_at: null,
    picked_up_at: null,
    cancelled_at: null,
  },
  {
    id: "order-006",
    shop_id: "demo-shop-001",
    order_number: 6,
    customer_name: "Marie L.",
    customer_phone: null,
    customer_email: "marie@email.com",
    customer_channel: "widget",
    items: [
      { product_id: "prod-001", name: "Croissant beurre", qty: 2, unit_price: 1.3, subtotal: 2.6 },
      { product_id: "prod-002", name: "Pain au chocolat", qty: 2, unit_price: 1.4, subtotal: 2.8 },
      { product_id: "prod-010", name: "Cafe expresso", qty: 1, unit_price: 1.5, subtotal: 1.5 },
    ],
    subtotal: 6.9,
    commission_amount: 0.1,
    total: 6.9,
    status: "cancelled",
    payment_status: "refunded",
    stripe_payment_intent_id: null,
    stripe_payment_link_id: null,
    stripe_payment_link_url: null,
    notes: "Annule - cliente ne viendra pas",
    created_at: h(2),
    updated_at: h(1.8),
    ready_at: null,
    picked_up_at: null,
    cancelled_at: h(1.8),
  },
];

export const DEMO_ANALYTICS = {
  today: {
    revenue: 58.8,
    orders: 6,
    avg: 9.8,
  },
  week: {
    revenue: 342.5,
    growth: 12.3,
  },
  month: {
    revenue: 1247.0,
  },
  topProduct: {
    name: "Croissant beurre",
    qty: 47,
  },
  hourly: Array.from({ length: 24 }, (_, i) => ({
    hour: i,
    count:
      i < 6 ? 0 :
      i < 8 ? Math.floor(Math.random() * 3) + 1 :
      i < 11 ? Math.floor(Math.random() * 6) + 4 :
      i < 14 ? Math.floor(Math.random() * 8) + 5 :
      i < 17 ? Math.floor(Math.random() * 3) + 1 :
      i < 20 ? Math.floor(Math.random() * 5) + 2 :
      i < 22 ? Math.floor(Math.random() * 2) :
      0,
  })),
  paymentSplit: {
    online: 72,
    on_pickup: 28,
  },
  dailyRevenue: Array.from({ length: 30 }, (_, i) => ({
    date: new Date(now.getTime() - (29 - i) * 86400000).toISOString().split("T")[0],
    revenue: Math.round((Math.random() * 60 + 25) * 100) / 100,
  })),
};

export function isDemoMode(): boolean {
  return process.env.NEXT_PUBLIC_DEMO_MODE === "true";
}
